# Generated by Django 5.2 on 2025-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0002_rename_kayttajat_kayttaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayttaja',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kayttaja',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
