# Generated by Django 5.2 on 2025-05-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0002_testiluokka'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testiluokka',
            new_name='UusiKayttaja',
        ),
    ]
