# Generated by Django 5.2 on 2025-05-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0003_rename_testiluokka_uusikayttaja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kayttaja',
        ),
    ]
