# Generated by Django 5.2 on 2025-05-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0005_uusikayttaja_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uusikayttaja',
            name='slug',
        ),
    ]
