# Generated by Django 5.2 on 2025-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0006_remove_uusikayttaja_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uusikayttaja',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
