# Generated by Django 4.2.21 on 2025-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0007_uusikayttaja_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UusiTila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(blank=True)),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('purpose', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rental', models.BooleanField(default=False)),
                ('loan', models.BooleanField(default=False)),
                ('reservation', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
