# Generated by Django 4.2.21 on 2025-07-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0008_uusitila'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uusitila',
            old_name='id',
            new_name='IDnumber',
        ),
    ]
