# Generated by Django 4.2.21 on 2025-07-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0009_rename_id_uusitila_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Size m²'),
        ),
    ]
