# Generated by Django 4.2.21 on 2025-07-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0010_alter_uusitila_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uusitila',
            old_name='IDnumber',
            new_name='idNumber',
        ),
    ]
