# Generated by Django 4.2.21 on 2025-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0011_rename_idnumber_uusitila_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='uusitila',
            name='privatespace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uusitila',
            name='publicspace',
            field=models.BooleanField(default=False),
        ),
    ]
