# Generated by Django 4.2.21 on 2025-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0012_uusitila_privatespace_uusitila_publicspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='capacity',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='size',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='Size m²'),
        ),
    ]
