# Generated by Django 4.2.21 on 2025-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0013_alter_uusitila_capacity_alter_uusitila_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uusitila',
            old_name='purpose',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='uusitila',
            name='privatespace',
        ),
        migrations.RemoveField(
            model_name='uusitila',
            name='publicspace',
        ),
        migrations.AddField(
            model_name='uusitila',
            name='availability',
            field=models.CharField(choices=[('rental', 'Vuokrattavissa'), ('loan', 'Lainattavissa'), ('reservation', 'Varattavissa')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='uusitila',
            name='publicity',
            field=models.CharField(choices=[('private', 'Yksityinen'), ('public', 'Julkinen')], default='', max_length=20),
        ),
    ]
