# Generated by Django 4.2.21 on 2025-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0014_rename_purpose_uusitila_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uusitila',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='uusitila',
            name='rental',
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='availability',
            field=models.CharField(choices=[('rental', 'Vuokrattavissa'), ('loan', 'Lainattavissa')], default='', max_length=20),
        ),
    ]
