# Generated by Django 4.2.21 on 2025-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0015_remove_uusitila_loan_remove_uusitila_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='availability',
            field=models.CharField(choices=[('rental', 'Vuokra'), ('loan', 'Laina')], default='', max_length=20),
        ),
    ]
