# Generated by Django 4.2.21 on 2025-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0016_alter_uusitila_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='availability',
            field=models.CharField(choices=[('rental', 'Vuokra'), ('loan', 'Laina')], default='Valitse tilan saatavuus', max_length=20),
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='publicity',
            field=models.CharField(choices=[('private', 'Yksityinen'), ('public', 'Julkinen')], default='Valitse tilan julkisuus', max_length=20),
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='type',
            field=models.CharField(choices=[('office', 'Toimisto'), ('meeting_room', 'Kokoushuone'), ('conference_room', 'Konferenssihuone'), ('event_space', 'Tapahtumatila')], default='Valitse tilan tyyppi', max_length=255),
        ),
    ]
