# Generated by Django 4.2.21 on 2025-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0017_alter_uusitila_availability_alter_uusitila_publicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='availability',
            field=models.CharField(choices=[('', 'Valitse tilan saatavuus'), ('rental', 'Vuokra'), ('loan', 'Laina')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='publicity',
            field=models.CharField(choices=[('', 'Valitse tilan julkisuus'), ('private', 'Yksityinen'), ('public', 'Julkinen')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='uusitila',
            name='type',
            field=models.CharField(choices=[('', 'Valitse tilan tyyppi'), ('office', 'Toimisto'), ('meeting_room', 'Kokoushuone'), ('conference_room', 'Konferenssihuone'), ('event_space', 'Tapahtumatila')], default='', max_length=255),
        ),
    ]
