# Generated by Django 4.2.21 on 2025-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0018_alter_uusitila_availability_alter_uusitila_publicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='type',
            field=models.CharField(choices=[('', 'Valitse tilan tyyppi'), ('Toimisto', 'Toimisto'), ('Kokoushuone', 'Kokoushuone'), ('Konferenssihuone', 'Konferenssihuone'), ('Tapahtumatila', 'Tapahtumatila')], default='', max_length=255),
        ),
    ]
