# Generated by Django 4.2.21 on 2025-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0019_alter_uusitila_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uusitila',
            name='type',
            field=models.CharField(choices=[('', 'Valitse tilan tyyppi'), ('office', 'Toimisto'), ('meeting_room', 'Kokoushuone'), ('conference_room', 'Konferenssihuone'), ('event_space', 'Tapahtumatila')], default='', max_length=255),
        ),
    ]
