# Generated by Django 4.2.21 on 2025-07-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0022_alter_uusitila_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uusitila',
            old_name='availability',
            new_name='service_type',
        ),
    ]
