# Generated by Django 4.2.21 on 2025-07-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0024_alter_uusitila_service_type_alter_uusitila_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UusiTila',
            new_name='Tilat',
        ),
    ]
