# Generated by Django 4.2.21 on 2025-07-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0025_rename_uusitila_tilat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tilat',
            new_name='Space',
        ),
    ]
