# Generated by Django 4.2.21 on 2025-07-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayttajat', '0026_rename_tilat_space'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UusiKayttaja',
            new_name='User',
        ),
    ]
