# Generated by Django 4.2.21 on 2025-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('idNumber', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('publicity', models.CharField(choices=[('', 'Valitse tilan julkisuus'), ('private', 'Yksityinen'), ('public', 'Julkinen')], default='', max_length=20)),
                ('service_type', models.CharField(choices=[('', 'Valitse tilan palvelutyyppi'), ('rental', 'Vuokra'), ('loan', 'Laina')], default='', max_length=20)),
                ('type', models.CharField(choices=[('', 'Valitse tilan tyyppi'), ('office', 'Toimisto'), ('meeting_room', 'Kokoushuone'), ('conference_room', 'Konferenssihuone'), ('event_space', 'Tapahtumatila')], default='', max_length=20)),
                ('size', models.CharField(blank=True, default='0', max_length=10, verbose_name='Size m²')),
                ('capacity', models.CharField(blank=True, default='0', max_length=10, verbose_name='Capacity')),
                ('reservation', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('joined_date', models.DateField(null=True)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
