<<<<<<< HEAD
# Generated by Django 4.2.21 on 2025-08-14 10:33
=======
# Generated by Django 4.2.21 on 2025-07-31 12:31
>>>>>>> f689510873e99ed1f8fea180acacc8cbc27801b5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
